/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author SCC
 */
public class Approved extends javax.swing.JFrame {

    /**
     * Creates new form Approved
     */
    public Approved() {
        initComponents();
        displayData();
    }
    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM customer WHERE pay_status ='Paid' ");
            tb.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
       
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        jid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stat = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        updatebtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText("Taxi Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 10, 200, 32);

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 220, 960, 350);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Customer Name");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(430, 50, 130, 40);

        pnum.setEditable(false);
        jPanel2.add(pnum);
        pnum.setBounds(580, 50, 233, 40);

        bname.setEditable(false);
        jPanel2.add(bname);
        bname.setBounds(160, 100, 233, 40);

        jid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jid.setForeground(new java.awt.Color(255, 255, 255));
        jid.setText("ID");
        jPanel2.add(jid);
        jid.setBounds(160, 50, 90, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Status");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(430, 100, 70, 40);

        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Approved", "Decline" }));
        jPanel2.add(stat);
        stat.setBounds(580, 100, 233, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Taxi Details");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 100, 100, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Customer ID :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(30, 50, 120, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(850, 10, 90, 40);

        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatebtnMouseExited(evt);
            }
        });

        jLabel4.setText("Update");

        javax.swing.GroupLayout updatebtnLayout = new javax.swing.GroupLayout(updatebtn);
        updatebtn.setLayout(updatebtnLayout);
        updatebtnLayout.setHorizontalGroup(
            updatebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebtnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        updatebtnLayout.setVerticalGroup(
            updatebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(updatebtn);
        updatebtn.setBounds(850, 100, 90, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Yellow Modern Black Friday Facebook Post.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 0, 960, 160);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Yellow Modern Black Friday Facebook Post.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 960, 160);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 960, 160);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(850, 10, 110, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Yellow Modern Black Friday Facebook Post.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(220, 0, 960, 580);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Yellow Modern Black Friday Facebook Post.png"))); // NOI18N
        jLabel8.setText("jLabel3");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 960, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:

        int r = tb.getSelectedRow();

        String id = tb.getValueAt(r, 0).toString();
        String firstname = tb.getValueAt(r, 6).toString();
        String lastname = tb.getValueAt(r, 2).toString();
        String stats = tb.getValueAt(r, 9).toString();

        jid.setText(id);
        bname.setText(firstname);
        pnum.setText(lastname);
        stat.setSelectedItem(stats);

    }//GEN-LAST:event_tbMouseClicked

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:

        String ids = jid.getText();
        String brand = bname.getText();
        String plate = pnum.getText();
        String Stat = stat.getSelectedItem().toString();

        try{

            dbConnector dbc = new dbConnector();

            String query = "UPDATE customer SET "
            + " status ='"+Stat+"' WHERE id='"+ids+"' ";

            if (dbc.insertData(query)) {
                JOptionPane.showMessageDialog(null, "Data Updated");
            }

        } catch (HeadlessException e){

            System.out.println(e);
        }
        jid.setText("");
        bname.setText("");
        pnum.setText("");
        stat.setSelectedItem("");
        displayData();
    }//GEN-LAST:event_updatebtnMouseClicked

    private void updatebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseEntered
        // TODO add your handling code here:

        updatebtn.setBackground(Color.GREEN);

    }//GEN-LAST:event_updatebtnMouseEntered

    private void updatebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseExited
        // TODO add your handling code here:

        updatebtn.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_updatebtnMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        jid.setText("");
        bname.setText("");
        pnum.setText("");
        stat.setSelectedItem("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        adminDashboard log = new adminDashboard();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Approved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Approved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Approved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Approved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Approved().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jid;
    private javax.swing.JTextField pnum;
    private javax.swing.JComboBox<String> stat;
    private javax.swing.JTable tb;
    private javax.swing.JPanel updatebtn;
    // End of variables declaration//GEN-END:variables
}
