/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import login_Register.login;
import static login_Register.login.passwordHash;
import net.proteanit.sql.DbUtils;
import userformscrud.add;

/**
 *
 * @author Admin
 */
public class taxi_info extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public taxi_info() {
        initComponents();
        displayData();
    }

    
    public void displayData(){
        try{
            dbConnector dbc = new dbConnector();
            ResultSet rs = dbc.getData("SELECT * FROM taxi_information");
            tb.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
       
        }
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        updatebtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        deletebtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        jid = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        stat = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addbtn = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Taxi Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 200, 32);

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 220, 770, 350);

        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatebtnMouseExited(evt);
            }
        });

        jLabel4.setText("Update");

        javax.swing.GroupLayout updatebtnLayout = new javax.swing.GroupLayout(updatebtn);
        updatebtn.setLayout(updatebtnLayout);
        updatebtnLayout.setHorizontalGroup(
            updatebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebtnLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        updatebtnLayout.setVerticalGroup(
            updatebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(updatebtn);
        updatebtn.setBounds(40, 360, 140, 60);

        deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletebtnMouseExited(evt);
            }
        });

        jLabel5.setText("Delete");

        javax.swing.GroupLayout deletebtnLayout = new javax.swing.GroupLayout(deletebtn);
        deletebtn.setLayout(deletebtnLayout);
        deletebtnLayout.setHorizontalGroup(
            deletebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletebtnLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        deletebtnLayout.setVerticalGroup(
            deletebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletebtnLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(deletebtn);
        deletebtn.setBounds(40, 470, 140, 60);

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Taxi Form");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(420, 0, 80, 54);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Plate No.");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(440, 50, 62, 40);
        jPanel2.add(pnum);
        pnum.setBounds(550, 50, 233, 40);
        jPanel2.add(bname);
        bname.setBounds(160, 100, 233, 40);

        jid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jid.setText("ID");
        jPanel2.add(jid);
        jid.setBounds(130, 50, 17, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Status");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(440, 100, 45, 40);

        stat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Rented" }));
        jPanel2.add(stat);
        stat.setBounds(550, 100, 233, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Brand Name");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(50, 100, 100, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Taxi ID :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(50, 50, 90, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(850, 10, 90, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Yellow Modern Black Friday Facebook Post.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 0, 940, 550);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Black Yellow Modern Black Friday Facebook Post.png"))); // NOI18N
        jLabel9.setText("jLabel3");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 940, 550);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 960, 160);

        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbtnMouseExited(evt);
            }
        });

        jLabel12.setText("ADD");

        javax.swing.GroupLayout addbtnLayout = new javax.swing.GroupLayout(addbtn);
        addbtn.setLayout(addbtnLayout);
        addbtnLayout.setHorizontalGroup(
            addbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtnLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel12)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        addbtnLayout.setVerticalGroup(
            addbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbtnLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(addbtn);
        addbtn.setBounds(40, 250, 140, 60);

        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(850, 10, 110, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yellow And Black Professional Cyber Monday Facebook Post.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 940, 580);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yellow And Black Professional Cyber Monday Facebook Post.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 0, 940, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        // TODO add your handling code here:
        
          if(bname.getText().isEmpty()||pnum.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "You need to Fill up all the details");
        }else{

            dbConnector dbc = new dbConnector();


            if(dbc.insertData("INSERT INTO taxi_information (bname, plateno, status) VALUES ('"+bname.getText()+"', "
                    + "'"+pnum.getText()+"', '"+stat.getSelectedItem()+"') ")){
                JOptionPane.showMessageDialog(null, "Inserted Successfully!");
                

            }else{
                JOptionPane.showMessageDialog(null, "NO INTERNET GAME");
            }
        }
          
        jid.setText("");
        bname.setText("");
        pnum.setText("");
        stat.setSelectedItem("");
          
          
          displayData();
        
        
    }//GEN-LAST:event_addbtnMouseClicked

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // TODO add your handling code here:
        
        int r = tb.getSelectedRow();
        
        String id = tb.getValueAt(r, 0).toString();
        String firstname = tb.getValueAt(r, 1).toString();
        String lastname = tb.getValueAt(r, 2).toString();
        String stats = tb.getValueAt(r, 3).toString();
                
        
        jid.setText(id);
        bname.setText(firstname);
        pnum.setText(lastname);
        stat.setSelectedItem(stats);
            
    }//GEN-LAST:event_tbMouseClicked

    private void addbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseEntered
        // TODO add your handling code here:
        
        addbtn.setBackground(Color.GREEN);
    }//GEN-LAST:event_addbtnMouseEntered

    private void addbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseExited
        // TODO add your handling code here:
        addbtn.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_addbtnMouseExited

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:

        
        String ids = jid.getText();
        String brand = bname.getText();
        String plate = pnum.getText();
        String Stat = stat.getSelectedItem().toString();
        
        
         
        
        try{
            
             dbConnector dbc = new dbConnector();
       
            
            String query = "UPDATE taxi_information SET bname ='"+brand+"', "
                + " plateno ='"+plate+"', "
                + " status ='"+Stat+"' WHERE id='"+ids+"' ";

            if (dbc.insertData(query)) {
            JOptionPane.showMessageDialog(null, "Data Updated");
            }
 
        } catch (HeadlessException e){
            
            System.out.println(e);
        }
        jid.setText("");
        bname.setText("");
        pnum.setText("");
        stat.setSelectedItem("");
        displayData();
    }//GEN-LAST:event_updatebtnMouseClicked

    private void deletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseClicked
        // TODO add your handling code here:
        
        String userid = jid.getText();
         
         dbConnector dbc = new dbConnector();
        
        try{
            if(dbc.deleteData("DELETE FROM taxi_information WHERE id = '"+userid+"' ")){
            
                JOptionPane.showMessageDialog(null, "Data Deleted");
            }
              
            
        } catch (Exception e){
            
            System.out.println(e);

        }
        jid.setText("");
        bname.setText("");
        pnum.setText(""); 
        stat.setSelectedItem("");
        displayData();
    }//GEN-LAST:event_deletebtnMouseClicked

    private void updatebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseEntered
        // TODO add your handling code here:
        
         updatebtn.setBackground(Color.GREEN);
        
    }//GEN-LAST:event_updatebtnMouseEntered

    private void updatebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseExited
        // TODO add your handling code here:
        
         updatebtn.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_updatebtnMouseExited

    private void deletebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseEntered
        // TODO add your handling code here:
        
         deletebtn.setBackground(Color.RED);
    }//GEN-LAST:event_deletebtnMouseEntered

    private void deletebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletebtnMouseExited
        // TODO add your handling code here:
        
         deletebtn.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_deletebtnMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:    
        adminDashboard log = new adminDashboard();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        jid.setText("");
        bname.setText("");
        pnum.setText("");
        stat.setSelectedItem("");

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taxi_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taxi_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taxi_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taxi_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taxi_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addbtn;
    private javax.swing.JTextField bname;
    private javax.swing.JPanel deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jid;
    private javax.swing.JTextField pnum;
    private javax.swing.JComboBox<String> stat;
    private javax.swing.JTable tb;
    private javax.swing.JPanel updatebtn;
    // End of variables declaration//GEN-END:variables
}
